version: '3.8'

services:
  testing-postgres:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-testing}'
    volumes:
      - ./test-api-db:/var/lib/postgresql/testing